### ISSUE TITLE
AttributeError: 'tqdm' object has no attribute 'pos'

### ISSUE THREAD

**Issue by liu-jc** [Tiiiger/SGC#5]
When I tried to run tuning.py, I got an error. 
How can I fix this? Could you specify which version of hyperopt you used? 

> Traceback (most recent call last):
  File "tuning.py", line 33, in <module>
    best = fmin(sgc_objective, space=space, algo=tpe.suggest, max_evals=60)
  File "/Users/liujc/anaconda3/lib/python3.6/site-packages/hyperopt/fmin.py", line 407, in fmin
    rval.exhaust()
  File "/Users/liujc/anaconda3/lib/python3.6/site-packages/hyperopt/fmin.py", line 262, in exhaust
    self.run(self.max_evals - n_done, block_until_done=self.asynchronous)
  File "/Users/liujc/anaconda3/lib/python3.6/site-packages/hyperopt/fmin.py", line 198, in run
    disable=not self.show_progressbar, dynamic_ncols=True,
  File "/Users/liujc/anaconda3/lib/python3.6/site-packages/tqdm/_tqdm.py", line 850, in __init__
    self.set_postfix(refresh=False, **postfix)
TypeError: set_postfix() argument after ** must be a mapping, not str
Exception ignored in: <object repr() failed>
Traceback (most recent call last):
  File "/Users/liujc/anaconda3/lib/python3.6/site-packages/tqdm/_tqdm.py", line 893, in __del__
    self.close()
  File "/Users/liujc/anaconda3/lib/python3.6/site-packages/tqdm/_tqdm.py", line 1111, in close
    pos = self.pos
AttributeError: 'tqdm' object has no attribute 'pos'

**Comment by Tiiiger** [comment]
I am using `hyperopt=0.1.1`. This error does not occur to me.

**Comment by liu-jc** [comment]
Problem solved. Thanks! They add a progress bar with tqdm in the new version.  It might be a bug in the new version of hyperopt. https://github.com/hyperopt/hyperopt/issues/454

**Comment by Tiiiger** [comment]
I see. I am glad that you figured it out.
